name: repo-miner 
schedule:
  # every month's first day
  - cron: "0 0 1 * *"


pipeline:
  stages:
    - id: get_gems_stage
      description: "stages for get basic gem infos"
      tasks:
        # id: <verb>
        # user_input:
        #   fields:
        #     - name: <what you will get back after the syntax> <noun>
        - id: get_gem_basic_infos  
          description: "get basic infos for all gems"
          type: read
          function: http-request-dynamic
          inputs:
            user_input:
              base_url: "https://rubygems.org/api/v1/search.json"
              pagination:
                name: page
                start: 1
                end: 2 
              params_fixed:
                - name: query
                  value: '*'
        - id: filter_gem_names
          description: "using jsonpath to filter out gem names"
          type: filter
          function: json-path 
          inputs:
            user_input:
              field: '$..name' 
            task_inputs:
              - from: get_gem_basic_infos 
                extract_field: text
        - id: flatten_gem_lists 
          description: "using flatten function to get a dataframe of gem names"
          type: transform 
          function: flatten-lists-to-dataframe 
          inputs:
            task_inputs:
              - from: filter_gem_names 
                extract_field: text
        - id: rename_to_gem_names
          description: "renamed 0 column into gem_names"
          type: transform
          function: rename-columns
          inputs:
            user_input:
              fields: 
                - 0: gem_names 
            task_inputs:
              - from: flatten_gem_lists
        - id: concat_gem_names_dataframe 
          description: "concat gem names dataframe"
          type: concat 
          function: concat
          inputs:
            task_inputs:
              - from: rename_to_gem_names   
    - id: call_gem_api_stage
      from:
        - get_gems_stage
      description: "stages for get basic gem infos"
      tasks:
        # id: <verb>
        # user_input:
        #   fields:
        #     - name: <what you will get back after the syntax> <noun>
        - id: replace_gem_name_in_apis  
          description: "replace text(gem name) inside another text(base url)"
          # need to discuss about type?
          # will read be better?
          type: transform
          function: api-format-replacement
          inputs:
            user_input:
              base_url: "https://rubygems.org/api/v1/gems/[gem_name].json"
              url_dynamic:
                - name: gem_name 
                  value: gem_names
            task_inputs:
              - from: concat_gem_names_dataframe
        - id: call_gem_apis  
          description: "call gem apis"
          type: read 
          function: http-request
          inputs:
            task_inputs:
              - from: replace_gem_name_in_apis 
                preserve_origin_data: True
        - id: rename_response_info
          description: "renamed 0 column into gem_names"
          type: transform
          function: rename-columns
          inputs:
            user_input:
              fields: 
                - 0: url,
                - status_code: status
                - text: body 
            task_inputs:
              - from: call_gem_apis 
        - id: concat_call_gem_api_dataframe 
          description: "concat gem api response dataframe"
          type: concat 
          function: concat
          inputs:
            task_inputs:
              - from: rename_response_info   



